// ============================================================
//  ShopManager.cs  —  Assets/Scripts/
//  Attach to the Merchant GameObject.
//
//  PHASE 2 REWRITE:
//  - Reads a List<ItemData> instead of relying on ShopItem components
//  - Generates shop buttons dynamically at runtime from that list
//  - ShopItem.cs is no longer needed and can be deleted
// ============================================================
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ShopManager : MonoBehaviour
{
    [Header("Items for sale — drag ItemData assets here")]
    public List<ItemData> itemsForSale = new List<ItemData>();

    [Header("Player")]
    public int playerGold = 100;

    [Header("UI — auto-wired by ShopUIBuilder")]
    public Text         goldText;
    public Transform    itemButtonContainer; // the panel buttons are parented to
    public GameObject   itemButtonPrefab;    // generated by ShopUIBuilder

    private InventoryManager  _inventoryManager;
    private List<Button>      _itemButtons = new List<Button>();

    void Start()
    {
        _inventoryManager = FindObjectOfType<InventoryManager>();
        if (_inventoryManager == null)
            Debug.LogError("ShopManager: No InventoryManager found in scene. " +
                           "Add it to the Player GameObject.");

        UpdateGoldDisplay();
        GenerateItemButtons();
    }

    // ── Generate buttons ──────────────────────────────────────

    void GenerateItemButtons()
    {
        if (itemButtonContainer == null || itemButtonPrefab == null)
        {
            Debug.LogWarning("ShopManager: itemButtonContainer or itemButtonPrefab " +
                             "not assigned. Run Build Shop UI.");
            return;
        }

        // Clear any existing buttons
        foreach (var btn in _itemButtons)
            if (btn != null) Destroy(btn.gameObject);
        _itemButtons.Clear();

        // Create one button per item in the list
        foreach (var item in itemsForSale)
        {
            var btnGO  = Instantiate(itemButtonPrefab, itemButtonContainer);
            btnGO.SetActive(true);
            var btn    = btnGO.GetComponent<Button>();
            var labels = btnGO.GetComponentsInChildren<Text>();

            // ShopUIBuilder names them: labels[0] = item name, labels[1] = price
            if (labels.Length >= 1) labels[0].text = item.itemName;
            if (labels.Length >= 2) labels[1].text = "Price: " + item.price;

            // Color swatch
            var swatch = btnGO.transform.Find("Swatch");
            if (swatch != null)
            {
                var img = swatch.GetComponent<Image>();
                if (img != null) img.color = item.outfitColor;
            }

            // Icon
            if (item.icon != null)
            {
                var iconObj = btnGO.transform.Find("Icon");
                if (iconObj != null)
                {
                    var img = iconObj.GetComponent<Image>();
                    if (img != null) img.sprite = item.icon;
                }
            }

            // Capture for lambda closure
            var capturedItem = item;
            btn.onClick.AddListener(() => TryBuyItem(capturedItem));

            _itemButtons.Add(btn);
        }

        RefreshButtonStates();
    }

    // ── Buy logic ─────────────────────────────────────────────

    public void TryBuyItem(ItemData item)
    {
        if (_inventoryManager.OwnsItem(item))
        {
            Debug.Log($"Already own {item.itemName}");
            return;
        }

        if (playerGold < item.price)
        {
            Debug.Log($"Not enough gold to buy {item.itemName}. " +
                      $"Need {item.price}, have {playerGold}.");
            return;
        }

        playerGold -= item.price;
        UpdateGoldDisplay();
        _inventoryManager.AddItem(item);
        RefreshButtonStates();
        Debug.Log($"Bought {item.itemName} for {item.price} gold.");
    }

    // ── UI helpers ────────────────────────────────────────────

    public void UpdateGoldDisplay()
    {
        if (goldText != null)
            goldText.text = "Gold: " + playerGold;
    }

    // Grey out buttons for items already owned or too expensive
    void RefreshButtonStates()
    {
        for (int i = 0; i < _itemButtons.Count; i++)
        {
            if (i >= itemsForSale.Count) break;
            var item   = itemsForSale[i];
            var btn    = _itemButtons[i];
            bool owned = _inventoryManager != null && _inventoryManager.OwnsItem(item);
            bool canAfford = playerGold >= item.price;
            btn.interactable = !owned && canAfford;
        }
    }

    //will be called inside ShopKeeperInteraction.Openshop later 
    //when dynamic restocking neededn
    public void RefreshShopItems() 
    {
        GenerateItemButtons();
    }


}
