// ============================================================
//  TopDownPlayerController.cs  –  place in Assets/Scripts/
//  Attach to the Player GameObject generated by RPGSceneBuilder.
//  Requires: Rigidbody (auto-added if missing), Capsule Collider.
// ============================================================
using UnityEngine;

[RequireComponent(typeof(Rigidbody))]
public class TopDownPlayerController : MonoBehaviour
{
    [Header("Movement")]
    public float moveSpeed     = 5f;
    public float rotateSpeed   = 720f;  // degrees per second

    [Header("Animation (optional)")]
    public Animator animator;           // leave empty if no animator

    Rigidbody  _rb;
    Vector3    _inputDir;
    static readonly int isMovingHash = Animator.StringToHash("isMoving");

    void Awake()
    {
        _rb = GetComponent<Rigidbody>();
        // Lock rotation so the capsule doesn't tip over
        _rb.constraints = RigidbodyConstraints.FreezeRotation;
        _rb.interpolation = RigidbodyInterpolation.Interpolate;
    }

    void Update()
    {
        // Read WASD / arrow keys
        float h = Input.GetAxisRaw("Horizontal");
        float v = Input.GetAxisRaw("Vertical");
        _inputDir = new Vector3(h, 0, v).normalized;

        // Rotate body to face movement direction
        if (_inputDir.sqrMagnitude > 0.01f)
        {
            Quaternion targetRot = Quaternion.LookRotation(_inputDir, Vector3.up);
            transform.rotation   = Quaternion.RotateTowards(transform.rotation,
                                       targetRot, rotateSpeed * Time.deltaTime);
        }

        // Animator integration
        if (animator != null)
            animator.SetBool(isMovingHash, _inputDir.magnitude > 0.1f);
    }

    void FixedUpdate()
    {
        Vector3 velocity = _inputDir.normalized * moveSpeed;
        velocity.y = _rb.velocity.y; // preserve gravity
        _rb.velocity = velocity;
    }

    

}
